/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PinVentana.java
 *
 * Created on 2/03/2014, 01:01:45 PM
 */
package fayerbird.gui;

import fayerbird.core.Autenticador;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import twitter4j.TwitterStream;
import twitter4j.TwitterException;
import twitter4j.auth.AccessToken;
import twitter4j.auth.RequestToken;

/**
 *
 * @author desiderantes
 */
public class PinVentana extends javax.swing.JFrame {

	private RequestToken reqToken;
	private AccessToken acToken;
	private TwitterStream twitter;
	private Autenticador auth;

	/** Creates new form PinVentana */
	public PinVentana(Autenticador auth) {
		this.auth = auth;
		this.reqToken = auth.getRequestToken();
		this.acToken = auth.getAccessToken();
		this.twitter = auth.getTwitter();

		initComponents();
		this.setTitle("La aplicación requiere autenticación");
		this.jLabel2.setText("Ruta: " + auth.getLogfile().getAbsolutePath());

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Ingrese el PIN:");

		jButton1.setText("Validar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField1.setToolTipText("El PIN sólo contiene números");
		jTextField1.setName("PINTextField"); // NOI18N

		jLabel2.setText("Ruta:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(26, 26, 26).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(37, 37, 37).addComponent(jButton1)).addComponent(jLabel2)).addContainerGap(20, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(33, 33, 33).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE).addComponent(jLabel2).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		String pin = jTextField1.getText();
		try {
			if (pin.length() > 0) {
				auth.setAccessToken(twitter.getOAuthAccessToken(auth.getRequestToken(), pin));
			} else {
				auth.setAccessToken(twitter.getOAuthAccessToken(auth.getRequestToken()));
			}
			System.out.println("\n\nAccess Tokens obtenidos con éxito.");
			System.out.println("Access Token: " + twitter.getOAuthAccessToken().getToken());
			System.out.println("Access Token secret: " + twitter.getOAuthAccessToken().getTokenSecret());
			auth.escribirArchivo();
			try {
				auth.atEnd();
				this.finalize();
			} catch (Throwable ex) {
				Logger.getLogger(PinVentana.class.getName()).log(Level.SEVERE, null, ex);
			}

		} catch (TwitterException ex) {
			JOptionPane.showMessageDialog(this, "El PIN " + pin + " no es válido", "PIN inválido", JOptionPane.ERROR_MESSAGE);
		}
	}//GEN-LAST:event_jButton1ActionPerformed
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
